version: '2'
services:
  web:
    image: dockercloud/hello-world
    ports:
      - 8080

  lb:
    image: dockercloud/haproxy
    ports:
      - 81:80
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

